### ISSUE TITLE
More than 250 redirects?

### ISSUE THREAD

**Issue by alahser** [nathangrigg/s3redirect#3]
For me, the script seems to hang at 250 redirects. I'm not sure what other information might be helpful, or, how to troubleshoot from here.

I simply divided my file into multiple files with no more than 250 in each to work around the issue.

**Comment by nathangrigg** [comment]
Thanks for the report. I will try to reproduce when I have a chance and hey back to you.

**Comment by alahser** [comment]
Let me know if I can add to the report. I'm happy to help. Your tool has
proved very helpful to me.

On Wed, Apr 30, 2014 at 8:15 PM, Nathan Grigg notifications@github.comwrote:

> Thanks for the report. I will try to reproduce when I have a chance and
> hey back to you.
> 
> > On Apr 30, 2014, at 9:57 AM, "Andrew P. Lahser" <
> > notifications@github.com> wrote:
> > 
> > For me, the script seems to hang at 250 redirects. I'm not sure what
> > other information might be helpful, or, how to troubleshoot from here.
> > 
> > I simply divided my file into multiple files with no more than 250 in
> > each to work around the issue.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nathangrigg/s3redirect/issues/3#issuecomment-41876084
> .

## 

Andrew
480-242-2762
twitter.com/andrewlahser

**Comment by nathangrigg** [comment]
So, I can't seem to reproduce the issue.

Can you tell me what version of boto you are using?

run the command `pip freeze | grep boto` or if that doesn't work, `python -c "import boto; print boto.__version__"`

**Comment by nathangrigg** [comment]
Closing because this issue is stale. Feel free to reopen if this continues to be a problem.
